FROM node:20-alpine AS build

WORKDIR /app

COPY Frontend/package*.json ./
RUN npm install --legacy-peer-deps

COPY Frontend/ .
RUN npm run build


# ---------- Runtime stage ----------
FROM node:20-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3001

CMD ["serve", "-s", "dist", "-l", "3001"]
